version: 2.1
jobs:
  build:
    orbs:
      docker-buildx: foodles/docker-buildx@0.0.1
    steps:
      steps:
        - docker-buildx:
            image: aianus/udptunnel
            docker-username: aianus
            docker-password: $DOCKERHUB_ACCESS_TOKEN
